# Generated by Django 4.2.3 on 2023-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('passw', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=60)),
                ('state', models.CharField(max_length=10)),
                ('last_log', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
